version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    expose:
      - 8090
    ports:
      - 8090:8090
    networks:
      - app

networks:
  app: